# Assignment #03
1. Explore College Scorecard website - https://collegescorecard.ed.gov/ 

2. Explore College Scorecard Data web page - https://collegescorecard.ed.gov/data/

3. Download and skim the documentation - https://collegescorecard.ed.gov/assets/FullDataDocumentation.pdf

4. Download the dataset - https://ed-public-download.app.cloud.gov/downloads/CollegeScorecard_Raw_Data.zip (265MB Zip File)

5. Unzip the file into a folder (there are many files, one for each school year)

6. Import the 2017-2018 school year file "MERGED2017_18_PP.csv" and explore:   

    * how many colleges or rows?   

    * how many variables or columns?   

    * Look at the first 20 rows   

    * look at the last 20 rows   

    * Look at a random sample of 20 rows    

7. Since there are too many variables to explore, many of which are not interesting. Modify your import statement to only import the following 9 variables:

- UNITID
- INSTNM
- CITY
- STABBR
- ZIP
- ADM_RATE
- UGDS
- TUITIONFEE_IN
- MN_EARN_WNE_P10 

8. Download and read the data dictionary file - https://collegescorecard.ed.gov/assets/CollegeScorecardDataDictionary.xlsx

Find out the definition of the above 9 variables and document the definitions in the Jupyter Notebook so that the readers will not need to repeat what you have done to know the meaning of these variables.

9. Use the predefined cells below to conduct and document your data exploration.

When in doubt, Google. Find examples and read documents/tutorials. 

Have fun!

In [1]:
# Import libraries
import pandas as pd

In [2]:
# load the 2017-2018 school year file "MERGED2017_18_PP.csv"  
df = pd.read_csv('MERGED2017_18_PP.csv',skipinitialspace = True, low_memory = False)
df.head(3)

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,ACCREDAGENCY,INSTURL,NPCURL,...,OMAWDP8_NOTFIRSTTIME_POOLED_SUPP,OMENRUP_NOTFIRSTTIME_POOLED_SUPP,OMENRYP_FULLTIME_POOLED_SUPP,OMENRAP_FULLTIME_POOLED_SUPP,OMAWDP8_FULLTIME_POOLED_SUPP,OMENRUP_FULLTIME_POOLED_SUPP,OMENRYP_PARTTIME_POOLED_SUPP,OMENRAP_PARTTIME_POOLED_SUPP,OMAWDP8_PARTTIME_POOLED_SUPP,OMENRUP_PARTTIME_POOLED_SUPP
0,100654,100200,1002,Alabama A & M University,Normal,AL,35762,Southern Association of Colleges and Schools C...,www.aamu.edu/,https://galileo.aamu.edu/NetPriceCalculator/np...,...,0.4048,0.2645,0.0137,0.315,0.3755,0.2958,0.0289,0.4224,0.2635,0.2852
1,100663,105200,1052,University of Alabama at Birmingham,Birmingham,AL,35294-0110,Southern Association of Colleges and Schools C...,www.uab.edu,uab.studentaidcalculator.com/survey.aspx,...,0.5448,0.12,0.0728,0.2583,0.5872,0.0817,0.1398,0.2618,0.3977,0.2008
2,100690,2503400,25034,Amridge University,Montgomery,AL,36117-3553,Southern Association of Colleges and Schools C...,www.amridgeuniversity.edu,www2.amridgeuniversity.edu:9091/,...,0.4647,0.1912,0.0148,0.3284,0.4391,0.2177,0.028,0.3645,0.4486,0.1589

In [3]:
# Find out how many colleges or rows?   
# Find out how many variables or columns?
print('The number of rows is:', df.shape[0])
print('The number of columns is:', df.shape[1])

The number of rows is: 7112
The number of columns is: 1977

In [4]:
# Look at the first 20 rows  
print(df.head(20))

    UNITID    OPEID  OPEID6                                     INSTNM  \
0   100654   100200    1002                   Alabama A & M University
1   100663   105200    1052        University of Alabama at Birmingham
2   100690  2503400   25034                         Amridge University
3   100706   105500    1055        University of Alabama in Huntsville
4   100724   100500    1005                   Alabama State University
5   100751   105100    1051                  The University of Alabama
6   100760   100700    1007          Central Alabama Community College
7   100812   100800    1008                    Athens State University
8   100830   831000    8310            Auburn University at Montgomery
9   100858   100900    1009                          Auburn University
10  100937   101200    1012                Birmingham Southern College
11  101028  1218200   12182     Chattahoochee Valley Community College
12  101073  1055400   10554                  Concordia College Alabama
13  101116  1303906   13039                South University-Montgomery
14  101143   101500    1015         Enterprise State Community College
15  101161   106000    1060          Coastal Alabama Community College
16  101189   100300    1003                        Faulkner University
17  101240   101700    1017            Gadsden State Community College
18  101277  4187200   41872       New Beginning College of Cosmetology
19  101286   101800    1018  George C Wallace Community College-Dothan

              CITY STABBR         ZIP  \
0           Normal     AL       35762
1       Birmingham     AL  35294-0110
2       Montgomery     AL  36117-3553
3       Huntsville     AL       35899
4       Montgomery     AL  36104-0271
5       Tuscaloosa     AL  35487-0166
6   Alexander City     AL       35010
7           Athens     AL       35611
8       Montgomery     AL  36117-3596
9           Auburn     AL       36849
10      Birmingham     AL       35254
11     Phenix City     AL       36869
12           Selma     AL       36701
13      Montgomery     AL       36116
14      Enterprise     AL  36330-1300
15     Bay Minette     AL  36507-2698
16      Montgomery     AL  36109-3390
17         Gadsden     AL       35903
18     Albertville     AL       35951
19          Dothan     AL  36303-9234

                                         ACCREDAGENCY  \
0   Southern Association of Colleges and Schools C...
1   Southern Association of Colleges and Schools C...
2   Southern Association of Colleges and Schools C...
3   Southern Association of Colleges and Schools C...
4   Southern Association of Colleges and Schools C...
5   Southern Association of Colleges and Schools C...
6   Southern Association of Colleges and Schools C...
7   Southern Association of Colleges and Schools C...
8   Southern Association of Colleges and Schools C...
9   Southern Association of Colleges and Schools C...
10  Southern Association of Colleges and Schools C...
11  Southern Association of Colleges and Schools C...
12                                                NaN
13  Southern Association of Colleges and Schools C...
14  Southern Association of Colleges and Schools C...
15  Southern Association of Colleges and Schools C...
16  Southern Association of Colleges and Schools C...
17  Southern Association of Colleges and Schools C...
18  National Accrediting Commission of Career Arts...
19  Southern Association of Colleges and Schools C...

                                              INSTURL  \
0                                       www.aamu.edu/
1                                         www.uab.edu
2                           www.amridgeuniversity.edu
3                                         www.uah.edu
4                                       www.alasu.edu
5                                         www.ua.edu/
6                                        www.cacc.edu
7                                      www.athens.edu
8                                         www.aum.edu
9                                      www.auburn.edu
10                                       www.bsc.edu/
11                                         www.cv.edu
12                                      www.ccal.edu/
13  www.southuniversity.edu/montgomery#location=Mo...
14                                       www.escc.edu
15                             www.coastalalabama.edu
16                                   www.faulkner.edu
17                               www.gadsdenstate.edu
18                             www.nbccosmetology.com
19                                    www.wallace.edu

                                               NPCURL  ...  \
0   https://galileo.aamu.edu/NetPriceCalculator/np...  ...
1            uab.studentaidcalculator.com/survey.aspx  ...
2                    www2.amridgeuniversity.edu:9091/  ...
3                                     finaid.uah.edu/  ...
4   www.alasu.edu/cost-aid/forms/calculator/index....  ...
5           financialaid.ua.edu/net-price-calculator/  ...
6          https://www.cacc.edu/net-price-calculator/  ...
7   https://24.athens.edu/apex/prod8/f?p=174:1:394...  ...
8   www.aum.edu/current-students/financial-informa...  ...
9   https://www.auburn.edu/admissions/costcalc/fre...  ...
10                   www.bsc.edu/fp/np-calculator.cfm  ...
11             www.cv.edu/about/consumer-information/  ...
12    www.ccal.edu/admissions/net-pricing-calculator/  ...
13  www.southuniversity.edu/montgomery/net-price-c...  ...
14           https://www.escc.edu/netprice/npcalc.htm  ...
15                             www.coastalalabama.edu  ...
16        www.faulkner.edu/net-price-calculator-form/  ...
17          www.gadsdenstate.edu/net-price-calculator  ...
18                 nbccosmetology.com/sa/nbc_zonemap/  ...
19          www.wallace.edu/net_price_calculator.aspx  ...

    OMAWDP8_NOTFIRSTTIME_POOLED_SUPP  OMENRUP_NOTFIRSTTIME_POOLED_SUPP  \
0                             0.4048                            0.2645
1                             0.5448                              0.12
2                             0.4647                            0.1912
3                             0.5121                            0.1593
4                             0.4226                            0.0754
5                             0.6376                            0.1267
6                             0.2807                            0.3502
7                             0.5627                            0.2276
8                             0.4884                            0.2048
9                             0.7038                             0.072
10                            0.6196                            0.0326
11                            0.2463                            0.1667
12                            0.0957                             0.505
13                            0.2574                            0.6426
14                             0.283                            0.3396
15                             0.297                            0.0998
16                            0.5333                            0.1701
17                            0.2818                            0.5138
18                               NaN                               NaN
19                            0.3583                             0.294

    OMENRYP_FULLTIME_POOLED_SUPP  OMENRAP_FULLTIME_POOLED_SUPP  \
0                         0.0137                         0.315
1                         0.0728                        0.2583
2                         0.0148                        0.3284
3                         0.0165                         0.323
4                         0.0254                        0.5327
5                         0.0073                        0.2431
6                         0.0142                        0.3794
7                         0.0109                        0.1797
8                         0.0134                        0.4208
9                         0.0062                        0.2026
10                        0.0031                        0.3303
11                        0.0155                        0.5959
12                         0.006                        0.2376
13                             0                        0.1263
14                        0.0095                        0.3663
15                        0.0119                        0.5981
16                        0.0057                        0.3406
17                        0.0215                        0.1641
18                           NaN                           NaN
19                        0.0221                        0.2986

    OMAWDP8_FULLTIME_POOLED_SUPP  OMENRUP_FULLTIME_POOLED_SUPP  \
0                         0.3755                        0.2958
1                         0.5872                        0.0817
2                         0.4391                        0.2177
3                         0.5361                        0.1243
4                         0.3133                        0.1286
5                         0.6817                        0.0679
6                         0.2206                        0.3858
7                          0.649                        0.1604
8                          0.327                        0.2388
9                         0.7405                        0.0506
10                        0.6319                        0.0348
11                        0.2216                         0.167
12                        0.1037                        0.6526
13                        0.2184                        0.6553
14                        0.3104                        0.3138
15                        0.2845                        0.1056
16                        0.4638                          0.19
17                        0.2742                        0.5402
18                           NaN                           NaN
19                        0.2993                        0.3799

    OMENRYP_PARTTIME_POOLED_SUPP  OMENRAP_PARTTIME_POOLED_SUPP  \
0                         0.0289                        0.4224
1                         0.1398                        0.2618
2                          0.028                        0.3645
3                         0.0245                        0.3947
4                          0.021                        0.5804
5                         0.0142                        0.2842
6                         0.0092                        0.3258
7                         0.0181                        0.2112
8                         0.0289                        0.3737
9                         0.0143                        0.3829
10                           NaN                           NaN
11                        0.0067                        0.5705
12                             0                        0.2075
13                        0.0035                        0.0804
14                         0.004                        0.4113
15                         0.019                        0.5704
16                        0.0112                        0.3825
17                        0.0835                        0.1191
18                           NaN                           NaN
19                         0.043                        0.2557

    OMAWDP8_PARTTIME_POOLED_SUPP  OMENRUP_PARTTIME_POOLED_SUPP
0                         0.2635                        0.2852
1                         0.3977                        0.2008
2                         0.4486                        0.1589
3                         0.3476                        0.2331
4                         0.1678                        0.2308
5                         0.4599                        0.2416
6                         0.2769                        0.3881
7                         0.4741                        0.2966
8                         0.2352                        0.3622
9                         0.4571                        0.1457
10                           NaN                           NaN
11                        0.1678                         0.255
12                        0.0094                         0.783
13                        0.2308                        0.6853
14                        0.1707                         0.414
15                        0.2838                        0.1268
16                        0.3582                        0.2481
17                        0.2338                        0.5636
18                           NaN                           NaN
19                        0.2743                         0.427

[20 rows x 1977 columns]

In [5]:
# Look at the last 20 rows 
print(df.tail(20))

        UNITID    OPEID  OPEID6  \
7092  47503311  4208611   42086
7093  47503312  4208612   42086
7094  47503313  4208613   42086
7095  47647001  4088301   40883
7096  47662901  4189101   41891
7097  47691101  4205801   42058
7098  48065701   869423    8694
7099  48079001  4218901   42189
7100  48092101  4220001   42200
7101  48133101  4213501   42135
7102  48154401  4220901   42209
7103  48305401  4224601   42246
7104  48312401   108131    1081
7105  48312402   108161    1081
7106  48312403   108162    1081
7107  48312404   108163    1081
7108  48387801  4223701   42237
7109  48400201  4228101   42281
7110  48778201  4221501   42215
7111  49005401  4182601   41826

                                                 INSTNM              CITY  \
7092   Relay Graduate School of Education - San Antonio       San Antonio
7093  Relay Graduate School of Education - Dallas-Fo...            Dallas
7094  Relay Graduate School of Education - Washingto...        Washington
7095                           WestMed College - Merced            Merced
7096                  Salon Institute - Columbus Campus      Lewis Center
7097          SAE Institute of Technology San Francisco        Emeryville
7098                  Rasmussen College - Overland Park     Overland Park
7099             Rocky Vista University - Southern Utah             Ivins
7100                 Designer Barber & Stylist School -        Springdale
7101             Sharp Edgez Barber Institute - Buffalo           Buffalo
7102  National Personal Training Institute of Cleveland  Highland Heights
7103             Barber School of Pittsburgh - Ambridge          Ambridge
7104                 Arizona State University at Tucson            Tucson
7105  Arizona State University - ASU Colleges at Lak...  Lake Havasu City
7106        Arizona State University at The Gila Valley          Thatcher
7107                   Arizona State University at Yuma              Yuma
7108  Bay Area Medical Academy - San Jose Satellite ...          San Jose
7109                        High Desert Medical College         Lancaster
7110                                       BCI - Malden            Malden
7111          Health Career Institute- Lauderdale Lakes  Lauderdale Lakes

     STABBR        ZIP                                       ACCREDAGENCY  \
7092     TX  782155155       Middle States Commission on Higher Education
7093     TX  752075155       Middle States Commission on Higher Education
7094     DC  200375155       Middle States Commission on Higher Education
7095     CA  953400000                                                NaN
7096     OH  430359153  National Accrediting Commission of Career Arts...
7097     CA      94608                                                NaN
7098     KS  662102786                         Higher Learning Commission
7099     UT  847386756                         Higher Learning Commission
7100     AR  727620990  National Accrediting Commission of Career Arts...
7101     NY  142170000                  Council on Occupational Education
7102     OH      44143  Accrediting Council for Continuing Education &...
7103     PA  150030000                                                NaN
7104     AZ  857454284                         Higher Learning Commission
7105     AZ  864036877                         Higher Learning Commission
7106     AZ  855525545                         Higher Learning Commission
7107     AZ  853656900                         Higher Learning Commission
7108     CA      95113  Accrediting Council for Independent Colleges a...
7109     CA  935340000  Accrediting Council for Continuing Education &...
7110     MA  021480000                                                NaN
7111     FL  333137268  Accrediting Commission of Career Schools and C...

                                         INSTURL NPCURL  ...  \
7092        relay.edu/location/relay-san-antonio    NaN  ...
7093  relay.edu/location/relay-dallas-fort-worth    NaN  ...
7094      relay.edu/location/relay-washington-dc    NaN  ...
7095                      www.westmedcollege.edu    NaN  ...
7096                      www.saloninstitute.edu    NaN  ...
7097                                 usa.sae.edu    NaN  ...
7098                               rasmussen.edu    NaN  ...
7099                         www.rvu.edu/rvu-su/    NaN  ...
7100                                         NaN    NaN  ...
7101           www.sharpedgezbarberinstitute.com    NaN  ...
7102                                nptiohio.edu    NaN  ...
7103                                 www.bsp.edu    NaN  ...
7104                                www.asu.edu/    NaN  ...
7105                                www.asu.edu/    NaN  ...
7106                                www.asu.edu/    NaN  ...
7107                                www.asu.edu/    NaN  ...
7108                             www.bamasf.com/    NaN  ...
7109                                www.hdmc.edu    NaN  ...
7110                            bostoncareer.org    NaN  ...
7111                                www.hci.edu/    NaN  ...

      OMAWDP8_NOTFIRSTTIME_POOLED_SUPP  OMENRUP_NOTFIRSTTIME_POOLED_SUPP  \
7092                               NaN                               NaN
7093                               NaN                               NaN
7094                               NaN                               NaN
7095                               NaN                               NaN
7096                               NaN                               NaN
7097                               NaN                               NaN
7098                               NaN                               NaN
7099                               NaN                               NaN
7100                               NaN                               NaN
7101                               NaN                               NaN
7102                               NaN                               NaN
7103                               NaN                               NaN
7104                               NaN                               NaN
7105                               NaN                               NaN
7106                               NaN                               NaN
7107                               NaN                               NaN
7108                               NaN                               NaN
7109                               NaN                               NaN
7110                               NaN                               NaN
7111                               NaN                               NaN

      OMENRYP_FULLTIME_POOLED_SUPP  OMENRAP_FULLTIME_POOLED_SUPP  \
7092                           NaN                           NaN
7093                           NaN                           NaN
7094                           NaN                           NaN
7095                           NaN                           NaN
7096                           NaN                           NaN
7097                           NaN                           NaN
7098                           NaN                           NaN
7099                           NaN                           NaN
7100                           NaN                           NaN
7101                           NaN                           NaN
7102                           NaN                           NaN
7103                           NaN                           NaN
7104                           NaN                           NaN
7105                           NaN                           NaN
7106                           NaN                           NaN
7107                           NaN                           NaN
7108                           NaN                           NaN
7109                           NaN                           NaN
7110                           NaN                           NaN
7111                           NaN                           NaN

      OMAWDP8_FULLTIME_POOLED_SUPP  OMENRUP_FULLTIME_POOLED_SUPP  \
7092                           NaN                           NaN
7093                           NaN                           NaN
7094                           NaN                           NaN
7095                           NaN                           NaN
7096                           NaN                           NaN
7097                           NaN                           NaN
7098                           NaN                           NaN
7099                           NaN                           NaN
7100                           NaN                           NaN
7101                           NaN                           NaN
7102                           NaN                           NaN
7103                           NaN                           NaN
7104                           NaN                           NaN
7105                           NaN                           NaN
7106                           NaN                           NaN
7107                           NaN                           NaN
7108                           NaN                           NaN
7109                           NaN                           NaN
7110                           NaN                           NaN
7111                           NaN                           NaN

      OMENRYP_PARTTIME_POOLED_SUPP  OMENRAP_PARTTIME_POOLED_SUPP  \
7092                           NaN                           NaN
7093                           NaN                           NaN
7094                           NaN                           NaN
7095                           NaN                           NaN
7096                           NaN                           NaN
7097                           NaN                           NaN
7098                           NaN                           NaN
7099                           NaN                           NaN
7100                           NaN                           NaN
7101                           NaN                           NaN
7102                           NaN                           NaN
7103                           NaN                           NaN
7104                           NaN                           NaN
7105                           NaN                           NaN
7106                           NaN                           NaN
7107                           NaN                           NaN
7108                           NaN                           NaN
7109                           NaN                           NaN
7110                           NaN                           NaN
7111                           NaN                           NaN

      OMAWDP8_PARTTIME_POOLED_SUPP  OMENRUP_PARTTIME_POOLED_SUPP
7092                           NaN                           NaN
7093                           NaN                           NaN
7094                           NaN                           NaN
7095                           NaN                           NaN
7096                           NaN                           NaN
7097                           NaN                           NaN
7098                           NaN                           NaN
7099                           NaN                           NaN
7100                           NaN                           NaN
7101                           NaN                           NaN
7102                           NaN                           NaN
7103                           NaN                           NaN
7104                           NaN                           NaN
7105                           NaN                           NaN
7106                           NaN                           NaN
7107                           NaN                           NaN
7108                           NaN                           NaN
7109                           NaN                           NaN
7110                           NaN                           NaN
7111                           NaN                           NaN

[20 rows x 1977 columns]

In [6]:
# Look at a random sample of 20 rows    
print(df.sample(20))

        UNITID    OPEID  OPEID6  \
5167    447175  2173207   21732
6800  16210401   830801    8308
2544    199139   297500    2975
4719    431983  2546300   25463
6748  13830903   869420    8694
1403    160472  2518300   25183
2184    188526   288500    2885
6789  15628601   195403    1954
3911    241182  2234900   22349
1307    156745   196400    1964
2922    210146   321900    3219
301     114415  1111203   11112
677     133553   147900    1479
5944    474924  1085802   10858
6082    480161  4038701   40387
6045    476966  4207900   42079
4971    442657  3098700   30987
147     107071   109800    1098
3330    220473   349500    3495
5572    456940  2069303   20693

                                                 INSTNM               CITY  \
5167                        Empire Beauty School-Aurora             Aurora
6800                     Cecil College - Elkton Station             Elkton
2544          University of North Carolina at Charlotte          Charlotte
4719                       Yeshiva of the Telshe Alumni          Riverdale
6748                    Rasmussen College-Tampa/Brandon              Tampa
1403                     South Louisiana Beauty College              Houma
2184     Albany College of Pharmacy and Health Sciences             Albany
6789             Bellarmine University - Bullitt County     Shepherdsville
3911               Antilles School of Technical Careers           San Juan
1307                                 Georgetown College         Georgetown
2922                         Southern Oregon University            Ashland
301   FIDM-Fashion Institute of Design & Merchandisi...             Irvine
677   Embry-Riddle Aeronautical University-Daytona B...      Daytona Beach
5944                Avalon School of Cosmetology-Layton             Layton
6082                               Ideal Beauty Academy         Louisville
6045                  SAE Institute of Technology-Miami  North Miami Beach
4971                        Milan Institute-Palm Desert        Palm Desert
147                          Henderson State University        Arkadelphia
3330                                 Johnson University          Knoxville
5572                          L'Ecole Culinaire-Memphis            Cordova

     STABBR         ZIP                                       ACCREDAGENCY  \
5167     CO       80017  National Accrediting Commission of Career Arts...
6800     MD   219215535       Middle States Commission on Higher Education
2544     NC  28223-0001  Southern Association of Colleges and Schools C...
4719     NY  10471-2897  Association of Advanced Rabbinical and Talmudi...
6748     FL   336109558                         Higher Learning Commission
1403     LA       70363                  Council on Occupational Education
2184     NY  12208-3492       Middle States Commission on Higher Education
6789     KY   401656122                                                NaN
3911     PR       00909     Accrediting Bureau of Health Education Schools
1307     KY  40324-1696  Southern Association of Colleges and Schools C...
2922     OR       97520  Northwest Commission on Colleges and Universities
301      CA  92614-5610  Western Association of Schools and Colleges Se...
677      FL  32114-3900  Southern Association of Colleges and Schools C...
5944     UT       84041  National Accrediting Commission of Career Arts...
6082     KY       40223  National Accrediting Commission of Career Arts...
6045     FL  33160-4307  Accrediting Council for Independent Colleges a...
4971     CA       92211                  Council on Occupational Education
147      AR  71999-0001                         Higher Learning Commission
3330     TN       37998  Southern Association of Colleges and Schools C...
5572     TN       38016                                                NaN

                              INSTURL  \
5167                   www.empire.edu
6800                              NaN
2544             https://www.uncc.edu
4719  https://yeshivatelshealumni.com
6748                www.rasmussen.edu
1403                    slbchouma.com
2184                    www.acphs.edu
6789                              NaN
3911                  antillespr.edu/
1307        www.georgetowncollege.edu
2922                      www.sou.edu
301                      www.FIDM.edu
677            daytonabeach.erau.edu/
5944  avalon.edu/locations/layton-ut/
6082           idealbeautyacademy.net
6045      usa.sae.edu/campuses/miami/
4971           www.milaninstitute.edu
147                       www.hsu.edu
3330            www.johnsonu.edu/Home
5572                   www.lecole.edu

                                                 NPCURL  ...  \
5167                www.empire.edu/net-price-calculator  ...
6800                                                NaN  ...
2544        https://calculator.uncc.edu/1516/npcalc.htm  ...
4719  https://sites.google.com/site/yeshivaofthetels...  ...
6748                                                NaN  ...
1403                                      slbchouma.com  ...
2184                     acphs.edu/net-price-calculator  ...
6789                                                NaN  ...
3911                      antillespr.com/npc/npcalc.htm  ...
1307  https://georgetowncollege.studentaidcalculator...  ...
2922  inside.sou.edu/assets/enrollment/apps/npcalc.html  ...
301       https://npc.collegeboard.org/student/app/fidm  ...
677           erau.studentaidcalculator.com/survey.aspx  ...
5944  avalon.edu/financial-aid/net-price-calculator-...  ...
6082       idealbeautyacademy.net/consumer-information/  ...
6045     sae-usa.com/netpricecalculator/nash/npcalc.htm  ...
4971                             www.milaninstitute.edu  ...
147                   www.hsu.edu/net-price-calculator/  ...
3330  https://www.johnsonu.edu/Tennessee/Future-Stud...  ...
5572                      www.vatterott.edu/calculator/  ...

      OMAWDP8_NOTFIRSTTIME_POOLED_SUPP  OMENRUP_NOTFIRSTTIME_POOLED_SUPP  \
5167                               NaN                               NaN
6800                               NaN                               NaN
2544                              0.59                            0.1768
4719                 PrivacySuppressed                 PrivacySuppressed
6748                               NaN                               NaN
1403                               NaN                               NaN
2184                            0.6628                            0.1163
6789                               NaN                               NaN
3911                               NaN                               NaN
1307                            0.5676                            0.4324
2922                            0.5456                            0.1175
301                              0.725                             0.275
677                             0.6351                            0.1327
5944                               NaN                               NaN
6082                               NaN                               NaN
6045                               NaN                               NaN
4971                               NaN                               NaN
147                             0.4389                            0.2349
3330                            0.5946                            0.3986
5572                            0.5638                             0.396

      OMENRYP_FULLTIME_POOLED_SUPP  OMENRAP_FULLTIME_POOLED_SUPP  \
5167                           NaN                           NaN
6800                           NaN                           NaN
2544                        0.0116                         0.271
4719                             0                        0.6452
6748                           NaN                           NaN
1403                           NaN                           NaN
2184                             0                        0.2302
6789                           NaN                           NaN
3911                           NaN                           NaN
1307                        0.0036                        0.0012
2922                        0.0066                        0.3561
301                              0                             0
677                         0.0104                        0.3062
5944                           NaN                           NaN
6082                           NaN                           NaN
6045                           NaN                           NaN
4971                           NaN                           NaN
147                         0.0085                        0.4193
3330                        0.0025                             0
5572                             0                        0.0389

      OMAWDP8_FULLTIME_POOLED_SUPP  OMENRUP_FULLTIME_POOLED_SUPP  \
5167                           NaN                           NaN
6800                           NaN                           NaN
2544                        0.5966                        0.1208
4719                         0.129                        0.2258
6748                           NaN                           NaN
1403                           NaN                           NaN
2184                        0.7374                        0.0324
6789                           NaN                           NaN
3911                           NaN                           NaN
1307                        0.6486                        0.3466
2922                        0.4846                        0.1527
301                            0.7                           0.3
677                         0.5801                        0.1032
5944                           NaN                           NaN
6082                           NaN                           NaN
6045                           NaN                           NaN
4971                           NaN                           NaN
147                         0.3952                         0.177
3330                        0.5909                        0.4066
5572                        0.5359                        0.4251

      OMENRYP_PARTTIME_POOLED_SUPP  OMENRAP_PARTTIME_POOLED_SUPP  \
5167                           NaN                           NaN
6800                           NaN                           NaN
2544                        0.0109                        0.2849
4719                           NaN                           NaN
6748                           NaN                           NaN
1403                           NaN                           NaN
2184             PrivacySuppressed             PrivacySuppressed
6789                           NaN                           NaN
3911                           NaN                           NaN
1307             PrivacySuppressed             PrivacySuppressed
2922                         0.019                        0.3631
301              PrivacySuppressed             PrivacySuppressed
677                              0                        0.3429
5944                           NaN                           NaN
6082                           NaN                           NaN
6045                           NaN                           NaN
4971                           NaN                           NaN
147                          0.007                        0.4266
3330             PrivacySuppressed             PrivacySuppressed
5572                           NaN                           NaN

      OMAWDP8_PARTTIME_POOLED_SUPP  OMENRUP_PARTTIME_POOLED_SUPP
5167                           NaN                           NaN
6800                           NaN                           NaN
2544                        0.4247                        0.2795
4719                           NaN                           NaN
6748                           NaN                           NaN
1403                           NaN                           NaN
2184             PrivacySuppressed             PrivacySuppressed
6789                           NaN                           NaN
3911                           NaN                           NaN
1307             PrivacySuppressed             PrivacySuppressed
2922                        0.3252                        0.2927
301              PrivacySuppressed             PrivacySuppressed
677                         0.1714                        0.4857
5944                           NaN                           NaN
6082                           NaN                           NaN
6045                           NaN                           NaN
4971                           NaN                           NaN
147                         0.2937                        0.2727
3330             PrivacySuppressed             PrivacySuppressed
5572                           NaN                           NaN

[20 rows x 1977 columns]

Read (with naked eyes, not computer) the dictionary and find out the definitions of the following 9 columns and copy the text next to the column name
- UNITID: The unique identification number assigned to postsecondary institutions as surveyed through IPEDS.          
- INSTNM: The institutionâ€™s name         
- CITY: The institution's location   (city)            
- ZIP: The institution's location    (zip code)
- ADM_RATE: The admissions rate at each campus     
- UGDS: Includes the number of degree/certificate-seeking undergraduates enrolled in the fall, as reported in the IPEDS Fall Enrollment component.             
- TUITIONFEE_IN: The cost data include the tuition and required fees of the institution. They are provided for in-state students         
- MN_EARN_WNE_P10: Mean earnings for the institutional aggregate of all federally aided students who enroll in an institution each year and who are employed but not enrolled. Earnings are defined as the sum of wages and deferred compensation from all non-duplicate W-2 forms received for each individual, plus positive self-employment earnings from Schedule SE.

In [7]:
# reimport the data with above 9 columns (ignore all other variables)
df = pd.read_csv('MERGED2017_18_PP.csv',skipinitialspace = True, usecols = ['UNITID','INSTNM','CITY','STABBR','ZIP','ADM_RATE','UGDS','TUITIONFEE_IN','MN_EARN_WNE_P10'])

In [15]:
# Find out the 10 colleges that are hardest to get in (top 10)
mydf = df[df.get('ADM_RATE') != 0]
print(mydf.nsmallest(10,'ADM_RATE'))

      UNITID                                       INSTNM          CITY  \
2978  211893                    Curtis Institute of Music  Philadelphia
3979  243744                          Stanford University      Stanford
1557  166027                           Harvard University     Cambridge
2302  192110                         The Juilliard School      New York
2123  186131                         Princeton University     Princeton
2233  190150  Columbia University in the City of New York      New York
633   130794                              Yale University     New Haven
1575  166683        Massachusetts Institute of Technology     Cambridge
212   110404           California Institute of Technology      Pasadena
427   121345                               Pomona College     Claremont

     STABBR         ZIP  ADM_RATE    UGDS  TUITIONFEE_IN  MN_EARN_WNE_P10
2978     PA       19103    0.0330   131.0         2675.0              NaN
3979     CA       94305    0.0473  7056.0        49617.0              NaN
1557     MA       02138    0.0516  7532.0        48949.0              NaN
2302     NY  10023-6588    0.0592   486.0        43170.0              NaN
2123     NJ  08544-0070    0.0641  5246.0        47140.0              NaN
2233     NY       10027    0.0661  8170.0        57208.0              NaN
633      CT       06520    0.0693  5742.0        51400.0              NaN
1575     MA  02139-4307    0.0717  4489.0        49892.0              NaN
212      CA       91125    0.0774   961.0        49908.0              NaN
427      CA  91711-6319    0.0836  1567.0        51075.0              NaN

In [16]:
# 10. Find out the average in-state tuition of top 10
mycol = df.get('TUITIONFEE_IN')
my10 = mycol.nlargest(10)
print("Average in state tuition for the top 10 reporting schools: $", my10.mean())

Average in state tuition for the top 10 reporting schools: $ 57050.4

In [17]:
# Find out the average earnings of graduates from the top 10
df5 = df.nlargest(10,'ADM_RATE')
mycol3 = df5.get('MN_EARN_WNE_P10')
print("The average earnings of graduates from the bottom 10 schools is: $", mycol3.mean(),"because data is listed as NULL for the 2017-2018 year")

The average earnings of graduates from the bottom 10 schools is: $ nan because data is listed as NULL for the 2017-2018 year

In [18]:
# Find out the 10 colleges that are easiest to get in (bottom 10)
print(df.nlargest(10,'ADM_RATE'))

      UNITID                                      INSTNM        CITY STABBR  \
24    101453               Heritage Christian University    Florence     AL
240   110918                California Christian College      Fresno     CA
370   118161    Lytles Redwood Empire Beauty College Inc  Santa Rosa     CA
472   123280    Shasta Bible College and Graduate School     Redding     CA
559   127653                           Naropa University     Boulder     CO
571   127954  Montessori Education Center of the Rockies     Boulder     CO
652   131830      National Conservatory of Dramatic Arts  Washington     DC
665   132842              Carlos Albizu University-Miami       Miami     FL
887   142090                         Boise Bible College       Boise     ID
1011  147165                            Midstate College      Peoria     IL

             ZIP  ADM_RATE   UGDS  TUITIONFEE_IN  MN_EARN_WNE_P10
24    35630-9977       1.0   59.0        11232.0              NaN
240        93727       1.0   16.0         9330.0              NaN
370        95403       1.0  158.0            NaN              NaN
472        96002       1.0   42.0        12060.0              NaN
559   80302-6697       1.0  384.0        31790.0              NaN
571        80301       1.0   16.0            NaN              NaN
652        20007       1.0   32.0         9900.0              NaN
665   33172-2209       1.0  236.0        12444.0              NaN
887   83714-1220       1.0  128.0        12080.0              NaN
1011  61614-3595       1.0  274.0        16230.0              NaN

In [19]:
# Find out the average in-state tuition of the bottom 10
df3 = df.nlargest(10,'ADM_RATE')
mycol1 = df3.get('TUITIONFEE_IN')
print("The average in state tuition for the bottom 10 schools is: $", mycol1.mean() )

The average in state tuition for the bottom 10 schools is: $ 14383.25

In [20]:
# Find out the average earnings of graduates from the bottom 10
df4 = df.nsmallest(10,'ADM_RATE')
mycol2 = df4.get('MN_EARN_WNE_P10')
print("The average earnings of graduates from the bottom 10 schools is: $", mycol2.mean(),"because data is listed as NULL for the 2017-2018 year")

The average earnings of graduates from the bottom 10 schools is: $ nan because data is listed as NULL for the 2017-2018 year